[package]
name = "webview"
version = "0.1.0"
authors = ["Boscop"]

[dependencies]
fnv = "1.0"

[dev-dependencies]
url = "1.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"
