[package]
name = "webview"
version = "0.1.0"
authors = ["Boscop"]
license = "MIT"
description = "Rust bindings for webview, a tiny cross-platform library to render web-based GUIs for desktop applications"
repository = "https://github.com/Boscop/webview-rs"

[dependencies]
fnv = "1.0"

[dev-dependencies]
urlencoding = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"
